language:
  - python

env:
  - SD=no

sudo: required

dist: trusty

install:
  - pip install -r app/requirements.txt
  - sudo apt-get update -qq
  - sudo apt-get install -y debootstrap curl

before_script:
  - curl -sL https://github.com/appc/acbuild/releases/download/v0.3.1/acbuild-v0.3.1.tar.gz -o acbuild.tar.gz
  - tar -xzvf acbuild.tar.gz

script:
  - PYTHONPATH=$TRAVIS_BUILD_DIR python -m unittest discover app/tests/
  - sudo make
  - sudo env PATH=$PATH:$TRAVIS_BUILD_DIR make aci
